name: Clojure CI

on:
  push:
    branches: 
      - develop 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set lein version
      run: sudo lein upgrade 2.8.3
    - name: Install dependencies
      run: lein deps
    - name: Run lint
      run: lein eastwood
    
  trigger:
  
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Trigger Jenkins Job
        uses: wei/curl@v1
        with:
            args: -X POST --data  PLATFORM_BRANCH=swym BRANCH_NAME=develop http://git:git0000@18.235.2.186:8080/job/Swym_Pipeline/buildWithParameters?token=swym


        
      
